CCSMCDS-65 Create EpisodeOfCare
ccsm-cds-tools/ccsm-cds-dashboard pull request #26
Opened 2023-11-15 19:12 UTC by yunwwang

This PR fixes issue https://jira.mitre.org/browse/CCSMCDS-56

The logic is migrated from https://github.com/ccsm-cds-tools/ccsm-cds-service/pull/25

2023-11-27 23:58 UTC, mickohanlon23 commented
I created [CCSMCDS-65](https://jira.mitre.org/browse/CCSMCDS-65) a while back to track the adding handling of Pregnancies denoted by Episodes of Care into the CCSM Dashboard. I'll move this into the Review column of the current sprint.

2023-11-29 03:05 UTC, mickohanlon23 requested changes
This looks good. Thanks for adding a testing directory! All tests pass, and the logic is based upon the logic in our CDS Hooks app (https://github.com/ccsm-cds-tools/ccsm-cds-service/pull/25/files#diff-578021ab2cd5452e245d346c76b9c3d078fd8a4667b826589179302721e58eabR349-R350), which we have tested and verified.

I made one comment about bumping the version of the CQL logic that we are bringing in through npm. If we use version 0.4.12, this PR will include the updates that we made to our logic around adding a check for pregnancy denoted by an Episode of Care.

General comment: We have not confirmed that this is the exact way that pregnancies will be represented by UMMC, so we may need to add to this translation if UMMC uses a different `EpisodeOfCare.type` code, or if UMMC has a different way of representing Pregnancy using a custom `Condition.code` or `Observation.code`. But for now, I think it makes sense to merge in what we have here as a start for translating pregnancies sent my UMMC. 

Thanks for making this change!

2023-11-29 03:05 UTC, mickohanlon23 commented on package.json
>      "ccsm-cds-with-tests": "^0.4.11",
```suggestion
    "ccsm-cds-with-tests": "^0.4.12",
```
Should we bump `ccsm-cds-with-tests` to 0.4.12, which adds the Episode of Care queries in our CQL? See https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/pull/119/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519.

2023-11-29 03:05 UTC, mickohanlon23 commented on src/hooks/useCds/translate.js
> +  'urn:oid:1.2.840.114350.1.13.88.3.7.2.726668' // BLD & COP
I don't think we have confirmed that these code systems are used by UMMC, but we can check this once we have them send us updated versions of the Pregnancy patient data after they have enabled the [EpisodeOfCare.Search](https://fhir.epic.com/Specifications?api=10157) API.

2023-11-29 03:05 UTC, mickohanlon23 commented on src/hooks/useCds/translate.js
> + * Add SNOMED CT Pregnancy coding to EpisdoeOfCare.type
```suggestion
 * Add SNOMED CT Pregnancy coding to EpisodeOfCare.type
```

2023-11-29 03:05 UTC, mickohanlon23 commented on test/fixtures/translate/patientData.json
> +        "display": "UNIV OF PITTSBURGH PHYSICIANS"
I think eventually it would make sense to replace this test fixture with patient data from UMMC. However, since they have not yet sent us data containing an Episode of Care (I believe they still need to grant us access to this API), this will suffice for now.

2023-11-29 03:05 UTC, mickohanlon23 commented on test/translate-test.js
> +      expect(episodeOfCare).to.not.be.empty;
Getting the following eslint warning for all the 'expect' calls in this file:
```
Expected an assignment or function call and instead saw an expression.
```
Do you know an easy way to fix this? Or should we disable that linting rule for this file (the tests are correctly running when I run `npm run test-mocha`)? From a quick online search, it seems like disabling the rule for the entire file may be the best approach.

2023-11-29 13:48 UTC, yunwwang commented on src/hooks/useCds/translate.js
> +  'urn:oid:1.2.840.114350.1.13.88.3.7.2.726668' // BLD & COP
Agree. This is a placeholder here for the potential Epic codes.

2023-11-29 13:50 UTC, yunwwang commented on test/fixtures/translate/patientData.json
> +        "display": "UNIV OF PITTSBURGH PHYSICIANS"
This is a mocked data for unit test but could be updated.

2023-11-30 00:36 UTC, mickohanlon23 commented
I tested the functionality by adding the following EpisodeOfCare Resource to the `Susan21 Holden65` patient in [testData.js](https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/blob/CCSMCDS-65-episode-of-care/src/test/fhir/testData.js). As a result, when I navigate to the `/tests-fhir` route (http://localhost:3000/tests-fhir/susan), the "PREGNANT" field in the dashboard now displays "Yes" instead of "No", matching the expected behavior of this PR!

<img width="1181" alt="Episode of Care Shows Pregnancy in Dashboard" src="https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/assets/51176978/6083eb88-82ec-43a1-9ecb-d0c78008122e">

2023-11-30 00:41 UTC, mickohanlon23 commented on package.json
>      "ccsm-cds-with-tests": "^0.4.11",
I'm going to add a commit after running `npm install`, so that the version is updated in package-lock.json as well.

2023-11-30 00:46 UTC, mickohanlon23 commented on test/translate-test.js
> +      expect(episodeOfCare).to.not.be.empty;
I disabled the `no-unused-expressions` eslint rule in https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/pull/26/commits/b3ee3f451c9859b58ebe981fb34c568ee33d65a6.

2023-11-30 00:47 UTC, mickohanlon23 approved these changes

2023-11-30 00:47 UTC, merged